
version: "3"
services:
  web:
    build:
      context: ./src
      dockerfile: ../Dockerfile
    volumes:
      - ./src:/opt/app
      - /opt/app/node_modules
      # Permite sincronizar la carpeta de trabajo durante el desarrollo 
      # de la aplicación
    depends_on:
      - db
      - dbMongo
    ports:
      - "8000:8000"
    
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db-data/postgreSql:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - DEBUG=false
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=domocity_db

  dbMongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db-data/mongoDb:/data/db
    networks:
      - backend
    environment:
      - DEBUG=false
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - DB_NAME=metricart_db


networks:
  backend:
