
version: "3"
services:

  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend



networks:
  backend:

volumes:
  db-data: